name: Build Kernel Module
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential linux-headers-$(uname -r)

      - name: Build module
        run: make

      - name: Upload ko artifact
        uses: actions/upload-artifact@v4
        with:
          name: rabbit-module
          path: module.ko
